buildNumber: unknown
buildTime: unknown
gitRevision: unknown
gitBranch: unknown
appName: unknown

spring:
  datasource:
    url: jdbc:mysql://100.93.20.121:13309/ecommerce_order_query_mysql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: 100.93.20.121
    port: 5672
    virtual-host: /
    username: rabbitmq-user
    password: rabbitmq-password

ecommerce:
  rabbit:
    publishX: order-query-publish-x
    publishDlx: order-query-publish-dlx
    publishDlq: order-query-publish-dlq
    receiveQ: order-query-receive-q
    receiveDlx: order-query-receive-dlx
    receiveDlq: order-query-receive-dlq
    receiveRecoverX: order-query-receive-recover-x