spring:
  datasource:
    url: jdbc:mysql://100.93.20.121:13306/ecommerce_order_mysql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: 100.93.20.121
    port: 5672
    virtual-host: /
    username: rabbitmq-user
    password: rabbitmq-password

ecommerce:
  order:
    jwtSecret: whateversecret
    jwtExpireMinutes: 30
  rabbit:
    publishX: order-publish-x
    publishDlx: order-publish-dlx
    publishDlq: order-publish-dlq
    receiveQ: order-receive-q
    receiveDlx: order-receive-dlx
    receiveDlq: order-receive-dlq8080
    receiveRecoverX: order-receive-recover-x