---
- name: Stop and remove previous Kibana container
  docker_container:
    name: elk-kibana
    state: absent
    keep_volumes: no

- name: Start the new Kibana container
  docker_container:
    name: elk-kibana
    image: docker.elastic.co/kibana/kibana:7.3.0
    state: started
    restart_policy: always
    ports:
      - "5601:5601"
    env:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es1.vagrant.local:9200
      XPACK_MONITORING_ENABLED: false
      TZ: "Asia/Shanghai"
